// <auto-generated />
using System;
using System.Collections.Generic;
using Altafraner.AfraApp;
using Altafraner.AfraApp.Otium.Domain.Models;
using Altafraner.AfraApp.Schuljahr.Domain.Models;
using Altafraner.AfraApp.User.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Altafraner.AfraApp.Migrations
{
    [DbContext(typeof(AfraAppContext))]
    [Migration("20260305130513_OptimizeDatabaseIndices")]
    partial class OptimizeDatabaseIndices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "anwesenheits_status", new[] { "anwesend", "entschuldigt", "fehlend" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "global_permission", new[] { "admin", "otiumsverantwortlich", "profundumsverantwortlich" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "mentor_type", new[] { "gm", "im" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "person_rolle", new[] { "mittelstufe", "oberstufe", "tutor" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "wochentyp", new[] { "h", "n" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Altafraner.AfraApp.Calendar.Domain.Models.CalendarSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffene_person_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_subscriptions");

                    b.HasIndex("BetroffenePersonId")
                        .HasDatabaseName("ix_calendar_subscriptions_betroffene_person_id");

                    b.ToTable("calendar_subscriptions");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheit", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<OtiumAnwesenheitsStatus>("Status")
                        .HasColumnType("anwesenheits_status")
                        .HasColumnName("status");

                    b.HasKey("BlockId", "StudentId")
                        .HasName("pk_otia_anwesenheiten");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_otia_anwesenheiten_student_id");

                    b.ToTable("otia_anwesenheiten");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheitsNotiz", b =>
                {
                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.HasKey("BlockId", "StudentId", "AuthorId")
                        .HasName("pk_otia_einschreibungs_notizen");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_otia_einschreibungs_notizen_author_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_otia_einschreibungs_notizen_student_id");

                    b.ToTable("otia_einschreibungs_notizen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("beschreibung");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("bezeichnung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("KategorieId")
                        .HasColumnType("uuid")
                        .HasColumnName("kategorie_id");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<int?>("MaxKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("max_klasse");

                    b.Property<int?>("MinKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("min_klasse");

                    b.HasKey("Id")
                        .HasName("pk_otia");

                    b.HasIndex("KategorieId")
                        .HasDatabaseName("ix_otia_kategorie_id");

                    b.ToTable("otia");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumEinschreibung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffene_person_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid>("TerminId")
                        .HasColumnType("uuid")
                        .HasColumnName("termin_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Interval", "Altafraner.AfraApp.Otium.Domain.Models.OtiumEinschreibung.Interval#TimeOnlyInterval", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<TimeSpan>("Duration")
                                .HasColumnType("interval");

                            b1.Property<TimeOnly>("Start")
                                .HasColumnType("time without time zone");
                        });

                    b.HasKey("Id")
                        .HasName("pk_otia_einschreibungen");

                    b.HasIndex("BetroffenePersonId")
                        .HasDatabaseName("ix_otia_einschreibungen_betroffene_person_id");

                    b.HasIndex("TerminId")
                        .HasDatabaseName("ix_otia_einschreibungen_termin_id");

                    b.ToTable("otia_einschreibungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bezeichnung");

                    b.Property<string>("CssColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("css_color");

                    b.Property<string>("Icon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("icon");

                    b.Property<bool>("IgnoreEnrollmentRule")
                        .HasColumnType("boolean")
                        .HasColumnName("ignore_enrollment_rule");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.PrimitiveCollection<List<Wochentyp>>("RequiredIn")
                        .IsRequired()
                        .HasColumnType("wochentyp[]")
                        .HasColumnName("required_in");

                    b.HasKey("Id")
                        .HasName("pk_otia_kategorien");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_otia_kategorien_parent_id");

                    b.ToTable("otia_kategorien");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IstAbgesagt")
                        .HasColumnType("boolean")
                        .HasColumnName("ist_abgesagt");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer")
                        .HasColumnName("max_einschreibungen");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ort");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("otium_id");

                    b.Property<string>("OverrideBeschreibung")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("override_beschreibung");

                    b.Property<string>("OverrideBezeichnung")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("override_bezeichnung");

                    b.Property<bool>("SindAnwesenheitenKontrolliert")
                        .HasColumnType("boolean")
                        .HasColumnName("sind_anwesenheiten_kontrolliert");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_id");

                    b.Property<Guid?>("WiederholungId")
                        .HasColumnType("uuid")
                        .HasColumnName("wiederholung_id");

                    b.HasKey("Id")
                        .HasName("pk_otia_termine");

                    b.HasIndex("BlockId")
                        .HasDatabaseName("ix_otia_termine_block_id");

                    b.HasIndex("OtiumId")
                        .HasDatabaseName("ix_otia_termine_otium_id");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_otia_termine_tutor_id");

                    b.HasIndex("WiederholungId")
                        .HasDatabaseName("ix_otia_termine_wiederholung_id");

                    b.ToTable("otia_termine");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<char>("Block")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(1)")
                        .HasColumnName("block")
                        .HasDefaultValueSql("''");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer")
                        .HasColumnName("max_einschreibungen");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ort");

                    b.Property<Guid>("OtiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("otium_id");

                    b.Property<Guid?>("TutorId")
                        .HasColumnType("uuid")
                        .HasColumnName("tutor_id");

                    b.Property<int>("Wochentag")
                        .HasColumnType("integer")
                        .HasColumnName("wochentag");

                    b.Property<Wochentyp>("Wochentyp")
                        .HasColumnType("wochentyp")
                        .HasColumnName("wochentyp");

                    b.HasKey("Id")
                        .HasName("pk_otia_wiederholungen");

                    b.HasIndex("OtiumId")
                        .HasDatabaseName("ix_otia_wiederholungen_otium_id");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_otia_wiederholungen_tutor_id");

                    b.ToTable("otia_wiederholungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackAnker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KategorieId")
                        .HasColumnType("uuid")
                        .HasColumnName("kategorie_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("pk_profundum_feedback_anker");

                    b.HasIndex("KategorieId")
                        .HasDatabaseName("ix_profundum_feedback_anker_kategorie_id");

                    b.ToTable("profundum_feedback_anker");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackEntry", b =>
                {
                    b.Property<Guid>("AnkerId")
                        .HasColumnType("uuid")
                        .HasColumnName("anker_id");

                    b.Property<Guid>("InstanzId")
                        .HasColumnType("uuid")
                        .HasColumnName("instanz_id");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffene_person_id");

                    b.Property<int>("Grad")
                        .HasColumnType("integer")
                        .HasColumnName("grad");

                    b.HasKey("AnkerId", "InstanzId", "BetroffenePersonId")
                        .HasName("pk_profundum_feedback_entries");

                    b.HasIndex("BetroffenePersonId")
                        .HasDatabaseName("ix_profundum_feedback_entries_betroffene_person_id");

                    b.HasIndex("InstanzId")
                        .HasDatabaseName("ix_profundum_feedback_entries_instanz_id");

                    b.ToTable("profundum_feedback_entries");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackKategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsFachlich")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fachlich");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("pk_profundum_feedback_kategories");

                    b.ToTable("profundum_feedback_kategories");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundaDefinitionDependency", b =>
                {
                    b.Property<Guid>("DependencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependency_id");

                    b.Property<Guid>("DependantId")
                        .HasColumnType("uuid")
                        .HasColumnName("dependant_id");

                    b.HasKey("DependencyId", "DependantId")
                        .HasName("pk_profundum_definition_dependencies");

                    b.HasIndex("DependantId")
                        .HasDatabaseName("ix_profundum_definition_dependencies_dependant_id");

                    b.ToTable("profundum_definition_dependencies");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumBelegWunsch", b =>
                {
                    b.Property<Guid>("ProfundumInstanzId")
                        .HasColumnType("uuid")
                        .HasColumnName("profundum_instanz_id");

                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffene_person_id");

                    b.Property<int>("Stufe")
                        .HasColumnType("integer")
                        .HasColumnName("stufe");

                    b.Property<Guid>("EinwahlZeitraumId")
                        .HasColumnType("uuid")
                        .HasColumnName("einwahl_zeitraum_id");

                    b.HasKey("ProfundumInstanzId", "BetroffenePersonId", "Stufe")
                        .HasName("pk_profunda_beleg_wuensche");

                    b.HasIndex("BetroffenePersonId")
                        .HasDatabaseName("ix_profunda_beleg_wuensche_betroffene_person_id");

                    b.HasIndex("EinwahlZeitraumId")
                        .HasDatabaseName("ix_profunda_beleg_wuensche_einwahl_zeitraum_id");

                    b.ToTable("profunda_beleg_wuensche");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("beschreibung");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bezeichnung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("KategorieId")
                        .HasColumnType("uuid")
                        .HasColumnName("kategorie_id");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<int?>("MaxKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("max_klasse");

                    b.Property<int?>("MinKlasse")
                        .HasColumnType("integer")
                        .HasColumnName("min_klasse");

                    b.HasKey("Id")
                        .HasName("pk_profunda");

                    b.HasIndex("KategorieId")
                        .HasDatabaseName("ix_profunda_kategorie_id");

                    b.ToTable("profunda");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinschreibung", b =>
                {
                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffene_person_id");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fixed");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<Guid?>("ProfundumInstanzId")
                        .HasColumnType("uuid")
                        .HasColumnName("profundum_instanz_id");

                    b.HasKey("BetroffenePersonId", "SlotId")
                        .HasName("pk_profunda_einschreibungen");

                    b.HasIndex("ProfundumInstanzId")
                        .HasDatabaseName("ix_profunda_einschreibungen_profundum_instanz_id");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("ix_profunda_einschreibungen_slot_id");

                    b.HasIndex("IsFixed", "BetroffenePersonId")
                        .HasDatabaseName("ix_profunda_einschreibungen_is_fixed_betroffene_person_id");

                    b.ToTable("profunda_einschreibungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinwahlZeitraum", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("EinwahlStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("einwahl_start");

                    b.Property<DateTime>("EinwahlStop")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("einwahl_stop");

                    b.HasKey("Id")
                        .HasName("pk_profundum_einwahl_zeitraeume");

                    b.ToTable("profundum_einwahl_zeitraeume");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumFachbereich", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.HasKey("Id")
                        .HasName("pk_profunda_fachbereiche");

                    b.ToTable("profunda_fachbereiche");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by_id");

                    b.Property<int?>("MaxEinschreibungen")
                        .HasColumnType("integer")
                        .HasColumnName("max_einschreibungen");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ort");

                    b.Property<Guid>("ProfundumId")
                        .HasColumnType("uuid")
                        .HasColumnName("profundum_id");

                    b.HasKey("Id")
                        .HasName("pk_profunda_instanzen");

                    b.HasIndex("ProfundumId")
                        .HasDatabaseName("ix_profunda_instanzen_profundum_id");

                    b.ToTable("profunda_instanzen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumKategorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("bezeichnung");

                    b.Property<bool>("ProfilProfundum")
                        .HasColumnType("boolean")
                        .HasColumnName("profil_profundum");

                    b.HasKey("Id")
                        .HasName("pk_profunda_kategorien");

                    b.ToTable("profunda_kategorien");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumProfilBefreiung", b =>
                {
                    b.Property<Guid>("BetroffenePersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("betroffene_person_id");

                    b.Property<int>("Jahr")
                        .HasColumnType("integer")
                        .HasColumnName("jahr");

                    b.Property<int>("Quartal")
                        .HasColumnType("integer")
                        .HasColumnName("quartal");

                    b.HasKey("BetroffenePersonId", "Jahr", "Quartal")
                        .HasName("pk_profundum_profil_befreiungen");

                    b.ToTable("profundum_profil_befreiungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EinwahlZeitraumId")
                        .HasColumnType("uuid")
                        .HasColumnName("einwahl_zeitraum_id");

                    b.Property<int>("Jahr")
                        .HasColumnType("integer")
                        .HasColumnName("jahr");

                    b.Property<int>("Quartal")
                        .HasColumnType("integer")
                        .HasColumnName("quartal");

                    b.Property<int>("Wochentag")
                        .HasColumnType("integer")
                        .HasColumnName("wochentag");

                    b.HasKey("Id")
                        .HasName("pk_profunda_slots");

                    b.HasIndex("EinwahlZeitraumId")
                        .HasDatabaseName("ix_profunda_slots_einwahl_zeitraum_id");

                    b.ToTable("profunda_slots");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumTermin", b =>
                {
                    b.Property<DateOnly>("Day")
                        .HasColumnType("date")
                        .HasColumnName("day");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Day")
                        .HasName("pk_profunda_termine");

                    b.HasIndex("SlotId")
                        .HasDatabaseName("ix_profunda_termine_slot_id");

                    b.ToTable("profunda_termine");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<char>("SchemaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("character(1)")
                        .HasColumnName("schema_id")
                        .HasDefaultValueSql("''");

                    b.Property<DateOnly>("SchultagKey")
                        .HasColumnType("date")
                        .HasColumnName("schultag_key");

                    b.Property<bool>("SindAnwesenheitenFehlernderKontrolliert")
                        .HasColumnType("boolean")
                        .HasColumnName("sind_anwesenheiten_fehlernder_kontrolliert");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("SchultagKey", "SchemaId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_schultag_key_schema_id");

                    b.ToTable("blocks");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Schultag", b =>
                {
                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date")
                        .HasColumnName("datum");

                    b.Property<Wochentyp>("Wochentyp")
                        .HasColumnType("wochentyp")
                        .HasColumnName("wochentyp");

                    b.HasKey("Datum")
                        .HasName("pk_schultage");

                    b.ToTable("schultage");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.MentorMenteeRelation", b =>
                {
                    b.Property<Guid>("MentorId")
                        .HasColumnType("uuid")
                        .HasColumnName("mentor_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<MentorType>("Type")
                        .HasColumnType("mentor_type")
                        .HasColumnName("type");

                    b.HasKey("MentorId", "StudentId", "Type")
                        .HasName("pk_mentor_mentee_relations");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_mentor_mentee_relations_student_id");

                    b.ToTable("mentor_mentee_relations");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.PrimitiveCollection<List<GlobalPermission>>("GlobalPermissions")
                        .IsRequired()
                        .HasColumnType("global_permission[]")
                        .HasColumnName("global_permissions");

                    b.Property<string>("Gruppe")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("gruppe");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<Guid?>("LdapObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("ldap_object_id");

                    b.Property<DateTime?>("LdapSyncFailureTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ldap_sync_failure_time");

                    b.Property<DateTime?>("LdapSyncTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ldap_sync_time");

                    b.Property<Rolle>("Rolle")
                        .HasColumnType("person_rolle")
                        .HasColumnName("rolle");

                    b.HasKey("Id")
                        .HasName("pk_personen");

                    b.HasIndex("Rolle")
                        .HasDatabaseName("ix_personen_rolle");

                    b.ToTable("personen");
                });

            modelBuilder.Entity("Altafraner.Backbone.EmailSchedulingModule.Models.ScheduledEmail<Altafraner.AfraApp.User.Domain.Models.Person>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_scheduled_emails");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_scheduled_emails_recipient_id");

                    b.ToTable("scheduled_emails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text")
                        .HasColumnName("friendly_name");

                    b.Property<string>("Xml")
                        .HasColumnType("text")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_data_protection_keys");

                    b.ToTable("data_protection_keys");
                });

            modelBuilder.Entity("OtiumDefinitionPerson", b =>
                {
                    b.Property<Guid>("VerantwortlicheId")
                        .HasColumnType("uuid")
                        .HasColumnName("verantwortliche_id");

                    b.Property<Guid>("VerwalteteOtiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("verwaltete_otia_id");

                    b.HasKey("VerantwortlicheId", "VerwalteteOtiaId")
                        .HasName("pk_otium_definition_person");

                    b.HasIndex("VerwalteteOtiaId")
                        .HasDatabaseName("ix_otium_definition_person_verwaltete_otia_id");

                    b.ToTable("otium_definition_person");
                });

            modelBuilder.Entity("PersonProfundumInstanz", b =>
                {
                    b.Property<Guid>("BetreuteProfundaId")
                        .HasColumnType("uuid")
                        .HasColumnName("betreute_profunda_id");

                    b.Property<Guid>("VerantwortlicheId")
                        .HasColumnType("uuid")
                        .HasColumnName("verantwortliche_id");

                    b.HasKey("BetreuteProfundaId", "VerantwortlicheId")
                        .HasName("pk_person_profundum_instanz");

                    b.HasIndex("VerantwortlicheId")
                        .HasDatabaseName("ix_person_profundum_instanz_verantwortliche_id");

                    b.ToTable("person_profundum_instanz");
                });

            modelBuilder.Entity("ProfundumDefinitionProfundumFachbereich", b =>
                {
                    b.Property<Guid>("FachbereicheId")
                        .HasColumnType("uuid")
                        .HasColumnName("fachbereiche_id");

                    b.Property<Guid>("ProfundaId")
                        .HasColumnType("uuid")
                        .HasColumnName("profunda_id");

                    b.HasKey("FachbereicheId", "ProfundaId")
                        .HasName("pk_profundum_definition_profundum_fachbereich");

                    b.HasIndex("ProfundaId")
                        .HasDatabaseName("ix_profundum_definition_profundum_fachbereich_profunda_id");

                    b.ToTable("profundum_definition_profundum_fachbereich");
                });

            modelBuilder.Entity("ProfundumFachbereichProfundumFeedbackKategorie", b =>
                {
                    b.Property<Guid>("FachbereicheId")
                        .HasColumnType("uuid")
                        .HasColumnName("fachbereiche_id");

                    b.Property<Guid>("ProfundumFeedbackKategorieId")
                        .HasColumnType("uuid")
                        .HasColumnName("profundum_feedback_kategorie_id");

                    b.HasKey("FachbereicheId", "ProfundumFeedbackKategorieId")
                        .HasName("pk_profundum_fachbereich_profundum_feedback_kategorie");

                    b.HasIndex("ProfundumFeedbackKategorieId")
                        .HasDatabaseName("ix_profundum_fachbereich_profundum_feedback_kategorie_profundu~");

                    b.ToTable("profundum_fachbereich_profundum_feedback_kategorie");
                });

            modelBuilder.Entity("ProfundumInstanzProfundumSlot", b =>
                {
                    b.Property<Guid>("ProfundumInstanzId")
                        .HasColumnType("uuid")
                        .HasColumnName("profundum_instanz_id");

                    b.Property<Guid>("SlotsId")
                        .HasColumnType("uuid")
                        .HasColumnName("slots_id");

                    b.HasKey("ProfundumInstanzId", "SlotsId")
                        .HasName("pk_profundum_instanz_profundum_slot");

                    b.HasIndex("SlotsId")
                        .HasDatabaseName("ix_profundum_instanz_profundum_slot_slots_id");

                    b.ToTable("profundum_instanz_profundum_slot");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Calendar.Domain.Models.CalendarSubscription", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany()
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_subscriptions_personen_betroffene_person_id");

                    b.Navigation("BetroffenePerson");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheit", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_anwesenheiten_blocks_block_id");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_anwesenheiten_personen_student_id");

                    b.Navigation("Block");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumAnwesenheitsNotiz", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_einschreibungs_notizen_personen_author_id");

                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_einschreibungs_notizen_blocks_block_id");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_einschreibungs_notizen_personen_student_id");

                    b.Navigation("Author");

                    b.Navigation("Block");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", "Kategorie")
                        .WithMany("Otia")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_otia_kategorien_kategorie_id");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumEinschreibung", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany("OtiaEinschreibungen")
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_einschreibungen_personen_betroffene_person_id");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", "Termin")
                        .WithMany("Enrollments")
                        .HasForeignKey("TerminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_einschreibungen_otia_termine_termin_id");

                    b.Navigation("BetroffenePerson");

                    b.Navigation("Termin");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_otia_kategorien_otia_kategorien_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", "Block")
                        .WithMany()
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_termine_blocks_block_id");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", "Otium")
                        .WithMany("Termine")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_termine_otia_otium_id");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .HasConstraintName("fk_otia_termine_personen_tutor_id");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", "Wiederholung")
                        .WithMany("Termine")
                        .HasForeignKey("WiederholungId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_otia_termine_otia_wiederholungen_wiederholung_id");

                    b.Navigation("Block");

                    b.Navigation("Otium");

                    b.Navigation("Tutor");

                    b.Navigation("Wiederholung");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", "Otium")
                        .WithMany("Wiederholungen")
                        .HasForeignKey("OtiumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otia_wiederholungen_otia_otium_id");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .HasConstraintName("fk_otia_wiederholungen_personen_tutor_id");

                    b.Navigation("Otium");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackAnker", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackKategorie", "Kategorie")
                        .WithMany()
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_feedback_anker_profundum_feedback_kategories_katego~");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackEntry", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackAnker", "Anker")
                        .WithMany()
                        .HasForeignKey("AnkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_feedback_entries_profundum_feedback_anker_anker_id");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany()
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_feedback_entries_personen_betroffene_person_id");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", "Instanz")
                        .WithMany()
                        .HasForeignKey("InstanzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_feedback_entries_profunda_instanzen_instanz_id");

                    b.Navigation("Anker");

                    b.Navigation("BetroffenePerson");

                    b.Navigation("Instanz");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundaDefinitionDependency", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", null)
                        .WithMany()
                        .HasForeignKey("DependantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_definition_dependencies_profunda_dependant_id");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", null)
                        .WithMany()
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_definition_dependencies_profunda_dependency_id");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumBelegWunsch", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany("ProfundaBelegwuensche")
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_beleg_wuensche_personen_betroffene_person_id");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinwahlZeitraum", "EinwahlZeitraum")
                        .WithMany()
                        .HasForeignKey("EinwahlZeitraumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_beleg_wuensche_profundum_einwahl_zeitraeume_einwahl_~");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", "ProfundumInstanz")
                        .WithMany()
                        .HasForeignKey("ProfundumInstanzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_beleg_wuensche_profunda_instanzen_profundum_instanz~");

                    b.Navigation("BetroffenePerson");

                    b.Navigation("EinwahlZeitraum");

                    b.Navigation("ProfundumInstanz");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumKategorie", "Kategorie")
                        .WithMany("Profunda")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_profunda_kategorien_kategorie_id");

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinschreibung", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany("ProfundaEinschreibungen")
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_einschreibungen_personen_betroffene_person_id");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", "ProfundumInstanz")
                        .WithMany("Einschreibungen")
                        .HasForeignKey("ProfundumInstanzId")
                        .HasConstraintName("fk_profunda_einschreibungen_profunda_instanzen_profundum_instan~");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_einschreibungen_profunda_slots_slot_id");

                    b.Navigation("BetroffenePerson");

                    b.Navigation("ProfundumInstanz");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", "Profundum")
                        .WithMany("Instanzen")
                        .HasForeignKey("ProfundumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_instanzen_profunda_profundum_id");

                    b.Navigation("Profundum");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumProfilBefreiung", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "BetroffenePerson")
                        .WithMany()
                        .HasForeignKey("BetroffenePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_profil_befreiungen_personen_betroffene_person_id");

                    b.Navigation("BetroffenePerson");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinwahlZeitraum", "EinwahlZeitraum")
                        .WithMany("Slots")
                        .HasForeignKey("EinwahlZeitraumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_slots_profundum_einwahl_zeitraeume_einwahl_zeitrau~");

                    b.Navigation("EinwahlZeitraum");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumTermin", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", "Slot")
                        .WithMany("Termine")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profunda_termine_profunda_slots_slot_id");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Block", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Schuljahr.Domain.Models.Schultag", "Schultag")
                        .WithMany("Blocks")
                        .HasForeignKey("SchultagKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_schultage_schultag_key");

                    b.Navigation("Schultag");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.MentorMenteeRelation", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mentor_mentee_relations_personen_mentor_id");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", null)
                        .WithMany("MentorMenteeRelations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mentor_mentee_relations_personen_student_id");
                });

            modelBuilder.Entity("Altafraner.Backbone.EmailSchedulingModule.Models.ScheduledEmail<Altafraner.AfraApp.User.Domain.Models.Person>", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scheduled_emails_personen_recipient_id");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("OtiumDefinitionPerson", b =>
                {
                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("VerantwortlicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otium_definition_person_personen_verantwortliche_id");

                    b.HasOne("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", null)
                        .WithMany()
                        .HasForeignKey("VerwalteteOtiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_otium_definition_person_otia_verwaltete_otia_id");
                });

            modelBuilder.Entity("PersonProfundumInstanz", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", null)
                        .WithMany()
                        .HasForeignKey("BetreuteProfundaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_profundum_instanz_profunda_instanzen_betreute_profun~");

                    b.HasOne("Altafraner.AfraApp.User.Domain.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("VerantwortlicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_person_profundum_instanz_personen_verantwortliche_id");
                });

            modelBuilder.Entity("ProfundumDefinitionProfundumFachbereich", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumFachbereich", null)
                        .WithMany()
                        .HasForeignKey("FachbereicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_definition_profundum_fachbereich_profunda_fachber~");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", null)
                        .WithMany()
                        .HasForeignKey("ProfundaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_definition_profundum_fachbereich_profunda_profund~");
                });

            modelBuilder.Entity("ProfundumFachbereichProfundumFeedbackKategorie", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumFachbereich", null)
                        .WithMany()
                        .HasForeignKey("FachbereicheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_fachbereich_profundum_feedback_kategorie_profunda~");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.Bewertung.ProfundumFeedbackKategorie", null)
                        .WithMany()
                        .HasForeignKey("ProfundumFeedbackKategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_fachbereich_profundum_feedback_kategorie_profundu~");
                });

            modelBuilder.Entity("ProfundumInstanzProfundumSlot", b =>
                {
                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", null)
                        .WithMany()
                        .HasForeignKey("ProfundumInstanzId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_instanz_profundum_slot_profunda_instanzen_profund~");

                    b.HasOne("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", null)
                        .WithMany()
                        .HasForeignKey("SlotsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profundum_instanz_profundum_slot_profunda_slots_slots_id");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumDefinition", b =>
                {
                    b.Navigation("Termine");

                    b.Navigation("Wiederholungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumKategorie", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Otia");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumTermin", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Otium.Domain.Models.OtiumWiederholung", b =>
                {
                    b.Navigation("Termine");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumDefinition", b =>
                {
                    b.Navigation("Instanzen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumEinwahlZeitraum", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumInstanz", b =>
                {
                    b.Navigation("Einschreibungen");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumKategorie", b =>
                {
                    b.Navigation("Profunda");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Profundum.Domain.Models.ProfundumSlot", b =>
                {
                    b.Navigation("Termine");
                });

            modelBuilder.Entity("Altafraner.AfraApp.Schuljahr.Domain.Models.Schultag", b =>
                {
                    b.Navigation("Blocks");
                });

            modelBuilder.Entity("Altafraner.AfraApp.User.Domain.Models.Person", b =>
                {
                    b.Navigation("MentorMenteeRelations");

                    b.Navigation("OtiaEinschreibungen");

                    b.Navigation("ProfundaBelegwuensche");

                    b.Navigation("ProfundaEinschreibungen");
                });
#pragma warning restore 612, 618
        }
    }
}
