name: backend

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ "*" ]
    paths:
      - '.github/workflows/backend.yml'
      - 'Backend/**'
  pull_request:
    branches: [ "*" ]
    paths:
      - 'Backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache Rust
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          Backend/Altafraner.Typst/typst_with_bindings/target
        key: rust-${{ runner.os }}-${{ hashFiles('Backend/**/Cargo.lock') }}
        restore-keys: |
          rust-${{ runner.os }}-

    - name: Build Rust bindings
      working-directory: Backend/Altafraner.Typst/typst_with_bindings
      run: cargo build --release
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore Backend/Altafraner.AfraApp/Altafraner.AfraApp.csproj
    - name: Build
      run: dotnet build --no-restore Backend/Altafraner.AfraApp/Altafraner.AfraApp.csproj
    - name: Restore test dependencies
      run: dotnet restore Backend/Altafraner.AfraApp.IntegrationTests/Altafraner.AfraApp.IntegrationTests.csproj
    - name: Build integration tests
      run: dotnet build --no-restore Backend/Altafraner.AfraApp.IntegrationTests/Altafraner.AfraApp.IntegrationTests.csproj
    - name: Run integration tests
      run: dotnet test --no-build Backend/Altafraner.AfraApp.IntegrationTests/Altafraner.AfraApp.IntegrationTests.csproj --logger trx --results-directory TestResults
